// export {default} from './Exercise2/Exercise2';
// export {default} from './Exercise3/Exercise3';
// export {default} from './Exercise4/App';
// export {default} from './Exercise5/ShoppingCart';
// export {default} from './Exercise6/Exercise6';
// export {default} from './Exercise7/Exercise7';
// export {default} from './Exercise8/Exercise8';
// export {default} from './Exercise9/Exercise9';
// export {default} from './Exercise10/Exercise10';
export {default} from './Exercise11/LoginForm';
